MCU = atmega32u4
BOOTLOADER = caterina
RGBLIGHT_ENABLE = yes       # Enable WS2812 RGB underlight.
SPLIT_KEYBOARD = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
DEFAULT_FOLDER = avalanche/rev4
