#pragma once

#define USE_I2C
// #define USE_SERIAL

#define TAP_CODE_DELAY 20

#define OLED_TIMEOUT 400000

#undef ENCODERS_PAD_A
#undef ENCODERS_PAD_B
#define ENCODERS_PAD_A { B5 }
#define ENCODERS_PAD_B { F4 }

#undef ENCODERS_PAD_A_RIGHT
#undef ENCODERS_PAD_B_RIGHT
#define ENCODERS_PAD_B_RIGHT { B5 }
#define ENCODERS_PAD_A_RIGHT { F4 }

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4

#define MASTER_LEFT

#undef RGBLED_NUM
#define RGBLED_NUM 52

#undef RGBLED_SPLIT
#define RGBLED_SPLIT { 26, 26 }

#undef RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LIMIT_VAL 200
#undef RGBLIGHT_HUE_STEP
#define RGBLIGHT_HUE_STEP 4
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_STATIC_LIGHT
// #define RGBLIGHT_EFFECT_BREATHING
// #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #define RGBLIGHT_EFFECT_STATIC_GRADIENT
// #define RGBLIGHT_EFFECT_BREATHE_MAX 125
// #define RGBLIGHT_EFFECT_BREATHE_CENTER 1.7
#define RGBLIGHT_SLEEP

/* lighting layers */
#ifdef RGBLIGHT_LAYERS
  #undef RGBLIGHT_LAYERS
#endif

// #define RGBLIGHT_LAYERS
// #define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF