ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = yes
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
MOUSEKEY_ENABLE = no
VIA_ENABLE = no
EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes
PIMORONI_TRACKBALL_ENABLE = no

# Disable unsupported hardware
AUDIO_SUPPORTED = no
BACKLIGHT_SUPPORTED = no