√#ifdef PERMISSIVE_HOLD
    #undef PERMISSIVE_HOLD
#endif

#ifdef IGNORE_MOD_TAP_INTERRUPT
    #undef IGNORE_MOD_TAP_INTERRUPT
#endif

#ifdef TAPPING_FORCE_HOLD
    #undef TAPPING_FORCE_HOLD
#endif

#ifdef TAPPING_FORCE_HOLD_PER_KEY
    #undef TAPPING_FORCE_HOLD_PER_KEY
#endif

#ifdef TAPPING_TERM
    #undef TAPPING_TERM
    #define TAPPING_TERM 250
#endif

#ifdef ENCODER_RESOLUTION
    #undef ENCODER_RESOLUTION
    #define ENCODER_RESOLUTIONS { 4, 4, 4 }
#endif

#undef ENCODERS_PAD_A
#define ENCODERS_PAD_A {B7, F1, D0}

#undef ENCODERS_PAD_B
#define ENCODERS_PAD_B {D5, B6, D1}

// COMBO STUFF
#define COMBO_COUNT 2
