OLED_ENABLE = yes
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = no
VIA_ENABLE = no
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
LTO_ENABLE = yes

# Disable unsupported hardware, maybe it reduces firmware size?
AUDIO_SUPPORTED = no
BACKLIGHT_SUPPORTED = no