LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = yes
MUSIC_ENABLE = no
MOUSEKEY_ENABLE = no
SWAP_HANDS_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = yes

#PER KEY RGB
RGB_MATRIX_ENABLE = no
